use_frameworks!

target 'ProtocolOrientedNetworking_Example' do
  pod 'ProtocolOrientedNetworking', :path => '../'

  target 'ProtocolOrientedNetworking_Tests' do
    inherit! :search_paths

    
  end
end
